name: Hello world workflow

on:
  push:
    branch:
      - main
  pull_request:
    - main
  workflow_dispatch:

  jobs:
    hello:
      runs_on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: "hello world"
          run: echo "Hello World"
          shell: bash

    goodbye:
      runs_on: ubuntu-latest
      steps:
        - name: goodbye World
          run: echo "goodbye world"\
          shell: bash
          
